### ISSUE TITLE
Create Schemas for Questions Table & Responses Table

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/consent-platform#11]
Create schemas in the consent database for the Consent Questions Table and the Participant Question Response Table, per the design documented here:

https://wiki.oicr.on.ca/display/OHCRN/%5BData+Model%5D+Consent+Platform

Note: responses will no longer have "updatedat" or be updated -- we will submit a new response each time and be able to track state/changes that way

When retrieving, retrieve the latest response for a given question

**Comment by anncatton** [comment]
Discussed with @mistryrn :
- rename User to Participant
- remove `createdAt` on `ParticipantResponse` model, just use `submittedAt`.
- make `ConsentQuestion` id human-readable, remove `question` field. use the id in the json file
- for clarity, create separate migrations for each of: `User` table renaming, create `ConsentQuestion` table, create `ParticipantResponse` table

**Comment by b-f-chan** [comment]
PR reviewed, not testing this in QA, closing
